import React, { useState, useEffect, useRef } from "react";
import { Claim } from "../../types";
import { useP2PDefense } from "../../hooks/useP2PDefense";
import { NavigationView } from "../layout/Sidebar";
import { Card } from "../ui/card";
import { P2PLiveCopilot } from "./P2PLiveCopilot";
import {
  PhoneCall,
  Printer,
  Copy,
  Check,
  ShieldWarning,
  ShieldCheck,
  ArrowLeft,
  Scales,
  WarningCircle,
  Sliders,
  CircleNotch,
  ArrowSquareOut,
  BookOpen,
  Headset,
  ArrowsClockwise,
} from "@phosphor-icons/react";
import { Button } from "../ui/button";
import { Badge } from "../ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../ui/dialog";
import { Input } from "../ui/input";
import { formatCurrency } from "../../lib/utils";
import { cn } from "../../lib/utils";

interface P2PDefenseStudioProps {
  claim: Claim;
  onNavigateView?: (view: NavigationView) => void;
}

export const P2PDefenseStudio: React.FC<P2PDefenseStudioProps> = ({
  claim,
  onNavigateView,
}) => {
  const {
    script,
    isLoadingScript,
    isSynthesizing,
    saveStatus,
    generateScript,
  } = useP2PDefense(claim);

  // 2-Mode architecture: 'playbook' (pre-call prep & print) vs 'copilot' (live call & AI simulation)
  const [activeMode, setActiveMode] = useState<"playbook" | "copilot">("playbook");
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [isCustomizeOpen, setIsCustomizeOpen] = useState<boolean>(false);
  const [checkedChecklist, setCheckedChecklist] = useState<Record<number, boolean>>({});

  // Customization Form state
  const [customPhysicianName, setCustomPhysicianName] = useState<string>(
    claim.appealContext?.sender?.name || claim.providerName || ""
  );
  const [customPhysicianSpecialty, setCustomPhysicianSpecialty] = useState<string>(
    claim.appealContext?.sender?.credentials || "Board-Certified Treating Specialist"
  );
  const [customMedicalDirectorRole, setCustomMedicalDirectorRole] = useState<string>(
    "Insurer Medical Director / Utilization Reviewer"
  );
  const [customStrategyNotes, setCustomStrategyNotes] = useState<string>("");

  // Auto-generate script on initial mount if none exists for this claim
  const hasAutoGeneratedRef = useRef<boolean>(false);
  useEffect(() => {
    if (!isLoadingScript && !script && !isSynthesizing && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      generateScript({
        physicianName: customPhysicianName || undefined,
        physicianSpecialty: customPhysicianSpecialty || undefined,
        medicalDirectorRole: customMedicalDirectorRole || undefined,
      }).catch((err) => {
        console.error("Auto-generate P2P script failed:", err);
      });
    }
  }, [isLoadingScript, script, isSynthesizing, generateScript, customPhysicianName, customPhysicianSpecialty, customMedicalDirectorRole]);

  // Copy helper
  const handleCopy = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => {
      setCopiedSection(null);
    }, 2000);
  };

  const payer = claim.patient?.insurancePayer || "Health Insurer";
  const cptList = (claim.cptCodes || []).join(", ");
  const icdList = (claim.icd10Codes || []).join(", ");

  const handlePrint = () => {
    if (!script) {
      window.print();
      return;
    }

    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      window.print();
      return;
    }

    printWindow.opener = null;

    const styles = Array.from(document.querySelectorAll("link[rel='stylesheet'], style"))
      .map((style) => style.outerHTML)
      .join("\n");

    const rapidChecklistHtml = (script.condensedCheatSheet?.rapidChecklist || [])
      .map(
        (item) => `
        <div style="display:flex;align-items:flex-start;gap:8px;padding:6px 8px;border:1px solid #cbd5e1;border-radius:6px;font-size:11px;">
          <div style="width:12px;height:12px;border:1.5px solid #64748b;border-radius:3px;margin-top:1px;flex-shrink:0;"></div>
          <span>${item}</span>
        </div>`
      )
      .join("");

    const mustSayHtml = (script.condensedCheatSheet?.mustSayPoints || [])
      .map(
        (pt) => `
        <li style="margin-bottom:6px;line-height:1.4;">
          <strong>&bull;</strong> ${pt}
        </li>`
      )
      .join("");

    const doNotConcedeHtml = (script.condensedCheatSheet?.doNotConcedePoints || [])
      .map(
        (pt) => `
        <li style="margin-bottom:6px;line-height:1.4;color:#991b1b;">
          <strong>&times;</strong> ${pt}
        </li>`
      )
      .join("");

    const trapCountersHtml = (script.disqualificationCounters || [])
      .slice(0, 3)
      .map(
        (trap, idx) => `
        <div style="margin-bottom:10px;padding:8px;border:1px solid #e2e8f0;border-radius:6px;background:#f8fafc;font-size:11px;">
          <div style="font-weight:bold;color:#b91c1c;margin-bottom:4px;">Insurer Trap #${idx + 1}: &ldquo;${trap.insurerTrapQuestion}&rdquo;</div>
          <div style="font-weight:500;color:#0f172a;line-height:1.4;"><strong>Physician Response:</strong> &ldquo;${trap.physicianDirectRebuttal}&rdquo;</div>
          <div style="font-size:10px;color:#64748b;margin-top:4px;"><strong>Leverage:</strong> ${trap.clinicalRationale} ${trap.regulatoryLeverage ? `&bull; ${trap.regulatoryLeverage}` : ""}</div>
        </div>`
      )
      .join("");

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>P2P Defense Cheat Sheet - Claim #${claim.claimNumber}</title>
        ${styles}
        <style>
          @page { size: letter portrait; margin: 10mm; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #fff !important; color: #0f172a !important; font-size: 11px; }
          .print-header { border-bottom: 2px solid #0284c7; padding-bottom: 8px; margin-bottom: 12px; }
          .print-badge { font-family: monospace; font-size: 10px; background: #f1f5f9; padding: 2px 6px; border-radius: 4px; border: 1px solid #cbd5e1; }
          .print-box { border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px; margin-bottom: 10px; }
        </style>
      </head>
      <body>
        <div class="printable-p2p-cheatsheet" style="max-width:800px;margin:0 auto;padding:10mm;font-family:Arial,Helvetica,sans-serif;color:#0f172a;background:#fff;">
          <div class="print-header" style="display:flex;justify-content:space-between;align-items:flex-start;">
            <div>
              <div style="font-size:10px;font-family:monospace;letter-spacing:1px;color:#0284c7;font-weight:bold;text-transform:uppercase;">
                ClaimHero Clinical Sentinel &bull; Physician P2P Defense Pocket Guide
              </div>
              <h1 style="font-size:16px;font-weight:bold;margin:4px 0 0 0;color:#0f172a;">
                Peer-to-Peer Defense Tele-Script
              </h1>
            </div>
            <div style="text-align:right;font-family:monospace;font-size:11px;">
              <div><strong>Claim #${claim.claimNumber}</strong></div>
              <div style="color:#64748b;">${payer} &bull; $${formatCurrency(claim.deniedAmount)}</div>
            </div>
          </div>

          <div style="display:grid;grid-template-columns:repeat(4, 1fr);gap:8px;padding:8px;background:#f8fafc;border:1px solid #cbd5e1;border-radius:6px;font-size:10px;font-family:monospace;margin-bottom:12px;">
            <div><span style="color:#64748b;">PATIENT:</span><br/><strong>${claim.patient?.name || "Patient"}</strong></div>
            <div><span style="color:#64748b;">MEMBER ID:</span><br/><strong>${claim.patient?.memberId || "N/A"}</strong></div>
            <div><span style="color:#64748b;">CPT CODES:</span><br/><strong style="color:#0284c7;">${cptList}</strong></div>
            <div><span style="color:#64748b;">ICD-10 CODES:</span><br/><strong style="color:#0284c7;">${icdList}</strong></div>
          </div>

          <div style="margin-bottom:12px;">
            <div style="font-size:10px;font-weight:bold;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;color:#0f172a;">
              Pre-Flight Call Checklist
            </div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">
              ${rapidChecklistHtml}
            </div>
          </div>

          <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;">
            <div style="border:1px solid #bae6fd;background:#f0f9ff;border-radius:6px;padding:8px;">
              <div style="font-size:10px;font-weight:bold;color:#0369a1;text-transform:uppercase;margin-bottom:6px;">
                4 Key Must-Say Points
              </div>
              <ul style="margin:0;padding-left:14px;font-size:10px;">
                ${mustSayHtml}
              </ul>
            </div>

            <div style="border:1px solid #fecdd3;background:#fff1f2;border-radius:6px;padding:8px;">
              <div style="font-size:10px;font-weight:bold;color:#be123c;text-transform:uppercase;margin-bottom:6px;">
                3 Do NOT Concede Points
              </div>
              <ul style="margin:0;padding-left:14px;font-size:10px;">
                ${doNotConcedeHtml}
              </ul>
            </div>
          </div>

          <div style="margin-bottom:12px;">
            <div style="font-size:10px;font-weight:bold;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;color:#0f172a;">
              Rapid Disqualification Counters
            </div>
            ${trapCountersHtml}
          </div>

          <div style="border:1px solid #fde68a;background:#fffbeb;border-radius:6px;padding:8px;font-size:10px;">
            <div style="font-weight:bold;color:#92400e;text-transform:uppercase;margin-bottom:4px;">
              Closing Written Determination Demand (ERISA 29 CFR &sect; 2560.503-1)
            </div>
            <div style="font-style:italic;line-height:1.4;color:#1e293b;">
              &ldquo;${script.condensedCheatSheet?.closingDemandStatement || script.statutoryDemands}&rdquo;
            </div>
          </div>
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.onafterprint = () => printWindow.close();
    window.setTimeout(() => printWindow.print(), 250);
  };

  const toggleChecklistItem = (idx: number) => {
    setCheckedChecklist((prev) => ({
      ...prev,
      [idx]: !prev[idx],
    }));
  };

  return (
    <div className="space-y-4 animate-fadeIn pb-16 flex flex-col font-sans">
      {/* Top Case Context & Navigation Bar */}
      <div className="rounded-xl border border-border/80 bg-card/70 backdrop-blur-xl p-3 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-3 no-print">
        {/* Left: Back & Patient Info */}
        <div className="flex items-center gap-2.5 flex-wrap min-w-0">
          <Button
            variant="ghost"
            size="xs"
            onClick={() => onNavigateView?.("studio")}
            className="gap-1.5 text-xs text-muted-foreground hover:text-foreground h-7 px-2.5 cursor-pointer"
            title="Return to Appeal Brief Studio"
          >
            <ArrowLeft className="size-3" />
            <span>Appeal Brief</span>
          </Button>

          <div className="h-4 w-px bg-border shrink-0" />

          <div className="flex items-center gap-2 min-w-0">
            <span className="font-semibold text-xs text-foreground truncate">
              {claim.patient?.name || "Patient Record"}
            </span>
            <Badge variant="outline" className="font-mono text-[10px] shrink-0">
              {claim.patient?.insurancePayer || "Insurer"}
            </Badge>
            <span className="text-[11px] font-mono text-muted-foreground hidden md:inline">
              #{claim.claimNumber}
            </span>
            <span className="text-[11px] font-mono text-primary font-bold">
              ${formatCurrency(claim.deniedAmount)}
            </span>
          </div>

          {saveStatus === "saving" && (
            <span className="flex items-center gap-1 text-[10px] font-mono text-muted-foreground animate-pulse ml-1">
              <CircleNotch className="size-2.5 animate-spin" />
              <span>Syncing</span>
            </span>
          )}
          {saveStatus === "saved" && (
            <span className="flex items-center gap-1 text-[10px] font-mono text-emerald-400 ml-1">
              <Check className="size-2.5" />
              <span>Synced</span>
            </span>
          )}
        </div>

        {/* Right: Mode Switcher & Global Studio Actions */}
        <div className="flex items-center gap-2 shrink-0 flex-wrap">
          {/* Mode Switcher Segmented Control */}
          <div className="flex items-center bg-secondary/70 p-0.5 rounded-lg border border-border/80">
            <button
              onClick={() => setActiveMode("playbook")}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-all cursor-pointer",
                activeMode === "playbook"
                  ? "bg-primary text-primary-foreground font-semibold shadow-xs"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              <BookOpen className="size-3.5" />
              <span>Defense Playbook</span>
            </button>
            <button
              onClick={() => setActiveMode("copilot")}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-all cursor-pointer",
                activeMode === "copilot"
                  ? "bg-primary text-primary-foreground font-semibold shadow-xs"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              <Headset className="size-3.5" />
              <span>Live Call Copilot</span>
              <span className="size-1.5 rounded-full bg-emerald-400 animate-ping" />
            </button>
          </div>

          {/* Customize Strategy */}
          <Button
            variant="outline"
            size="xs"
            onClick={() => setIsCustomizeOpen(true)}
            className="h-7 rounded-md px-2.5 text-xs gap-1.5 border-border/70 text-foreground cursor-pointer"
            title="Customize physician credentials and reviewer details"
          >
            <Sliders className="size-3" />
            <span>Customize</span>
          </Button>

          {/* Print Pocket Sheet */}
          <Button
            variant="outline"
            size="xs"
            onClick={handlePrint}
            className="h-7 rounded-md px-2.5 text-xs gap-1.5 border-border/70 text-foreground cursor-pointer"
            title="Print single-sheet physical clipboard guide"
          >
            <Printer className="size-3" />
            <span>Print Sheet</span>
          </Button>

          {/* Re-Synthesize */}
          <Button
            variant="outline"
            size="xs"
            onClick={() =>
              generateScript({
                physicianName: customPhysicianName || undefined,
                physicianSpecialty: customPhysicianSpecialty || undefined,
                medicalDirectorRole: customMedicalDirectorRole || undefined,
                customStrategyNotes: customStrategyNotes || undefined,
              })
            }
            disabled={isSynthesizing}
            className="h-7 rounded-md px-2.5 text-xs gap-1.5 border-border/70 text-foreground cursor-pointer"
            title="Regenerate defense script from clinical policy data"
          >
            {isSynthesizing ? (
              <CircleNotch className="size-3 animate-spin text-primary" />
            ) : (
              <ArrowsClockwise className="size-3" />
            )}
            <span>{isSynthesizing ? "Synthesizing..." : "Re-Synthesize"}</span>
          </Button>
        </div>
      </div>

      {/* Loading Skeleton */}
      {isSynthesizing && !script && (
        <Card className="p-8 flex flex-col items-center justify-center space-y-3 bg-card/60 backdrop-blur-md border-border/80">
          <CircleNotch className="size-6 text-primary animate-spin" />
          <div className="text-xs font-mono text-muted-foreground">
            Synthesizing grounded P2P defense playbook and clinical policy rebuttals...
          </div>
        </Card>
      )}

      {/* MODE 1: DEFENSE PLAYBOOK (Pre-Call Preparation & Battle Card) */}
      {activeMode === "playbook" && script && (
        <div className="space-y-4 no-print">
          {/* Quick Case Factstrip & Primary CTA Banner */}
          <Card className="p-3.5 rounded-xl border-border/80 bg-card/75 backdrop-blur-xl shadow-xs">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">
                <div>
                  <span className="text-muted-foreground block text-[10px] uppercase font-semibold">
                    Adverse Code
                  </span>
                  <span className="font-bold text-destructive">
                    {claim.denialReasonCode || "CO-50"}
                  </span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-[10px] uppercase font-semibold">
                    Disputed CPT
                  </span>
                  <span className="font-semibold text-primary">{cptList || "N/A"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-[10px] uppercase font-semibold">
                    Diagnosis ICD-10
                  </span>
                  <span className="font-semibold text-primary">{icdList || "N/A"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-[10px] uppercase font-semibold">
                    Member ID
                  </span>
                  <span className="font-semibold text-foreground">
                    {claim.patient?.memberId || "N/A"}
                  </span>
                </div>
              </div>

              <div className="flex items-center gap-2 shrink-0 pt-2 md:pt-0 border-t md:border-t-0 border-border/50">
                <Button
                  size="sm"
                  onClick={() => setActiveMode("copilot")}
                  className="h-8 rounded-lg px-3 text-xs font-semibold gap-1.5 bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs cursor-pointer"
                >
                  <PhoneCall className="size-3.5" />
                  <span>Launch Live Call Copilot</span>
                </Button>
              </div>
            </div>
          </Card>

          {/* Pre-Flight Checklist Grid */}
          {script.condensedCheatSheet?.rapidChecklist && (
            <Card className="p-3.5 rounded-xl border-border/80 bg-card/70 backdrop-blur-xl space-y-2.5 shadow-xs">
              <div className="flex items-center justify-between">
                <div className="text-xs font-bold font-sans uppercase tracking-wider text-foreground flex items-center gap-1.5">
                  <ShieldCheck className="size-4 text-emerald-400" />
                  <span>Pre-Flight Checklist (Statutory Mandates)</span>
                </div>
                <span className="text-[11px] text-muted-foreground">
                  Tap to verify before dialing
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                {script.condensedCheatSheet.rapidChecklist.map((item, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => toggleChecklistItem(idx)}
                    className={cn(
                      "flex items-start gap-2.5 p-2 rounded-md border text-left transition-colors cursor-pointer",
                      checkedChecklist[idx]
                        ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300 line-through opacity-80"
                        : "border-border/70 bg-card/60 text-foreground hover:bg-card/90"
                    )}
                  >
                    <div
                      className={cn(
                        "size-4 rounded border flex items-center justify-center shrink-0 mt-0.5 transition-colors",
                        checkedChecklist[idx]
                          ? "border-emerald-400 bg-emerald-500 text-white"
                          : "border-muted-foreground/40 bg-transparent"
                      )}
                    >
                      {checkedChecklist[idx] && <Check className="size-3" />}
                    </div>
                    <span className="leading-snug">{item}</span>
                  </button>
                ))}
              </div>
            </Card>
          )}

          {/* Phase 1: Statutory Opening Card */}
          <Card className="rounded-xl border border-border/80 bg-card/75 backdrop-blur-xl p-4 space-y-3 shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                  Phase 1 &bull; 0:00 - 0:45
                </span>
                <h2 className="text-sm font-semibold text-foreground font-sans">
                  Statutory Opening & Reviewer Credential Inquest
                </h2>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleCopy(script.openingStatutoryStatement, "p1")}
                className="h-7 text-xs px-2 text-muted-foreground hover:text-foreground cursor-pointer gap-1"
              >
                {copiedSection === "p1" ? (
                  <Check className="size-3 text-emerald-400" />
                ) : (
                  <Copy className="size-3" />
                )}
                <span>{copiedSection === "p1" ? "Copied" : "Copy"}</span>
              </Button>
            </div>

            <p className="text-xs text-muted-foreground leading-relaxed">
              Read directly upon line connection to establish legal footing under ERISA 29 CFR &sect; 2560.503-1 and state utilization review laws:
            </p>

            <div className="p-3.5 rounded-lg bg-secondary/60 border border-border/80 text-foreground text-sm leading-relaxed">
              &ldquo;{script.openingStatutoryStatement}&rdquo;
            </div>

            <div className="flex items-center gap-2 text-xs text-amber-400 bg-amber-500/10 border border-amber-500/20 px-3 py-2 rounded-md leading-relaxed">
              <ShieldWarning className="size-4 shrink-0" />
              <span>
                <strong>Tactical Note:</strong> If the reviewer admits they are not board-certified in this exact specialty, note their full name and license state immediately for state same-specialty grievance complaints.
              </span>
            </div>
          </Card>

          {/* Phase 2: CPB Section Citations & Clinical Counter-Offensive */}
          <Card className="rounded-xl border border-border/80 bg-card/75 backdrop-blur-xl p-4 space-y-3 shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                  Phase 2 &bull; 0:45 - 2:00
                </span>
                <h2 className="text-sm font-semibold text-foreground font-sans">
                  Exact Policy Citations & Patient Chart Proof
                </h2>
              </div>
              <Badge variant="outline" className="text-[10px] border-primary/30 text-primary">
                {script.clinicalPolicyCitations.length} Grounded Points
              </Badge>
            </div>

            <div className="grid grid-cols-1 gap-3">
              {script.clinicalPolicyCitations.map((cit, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-lg border border-border/70 bg-card/50 space-y-2 text-xs"
                >
                  <div className="flex items-center justify-between flex-wrap gap-1">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-primary">
                        Citation {idx + 1}:
                      </span>
                      <span className="font-semibold text-foreground">
                        {cit.cpbTitle}
                      </span>
                      <Badge variant="outline" className="font-mono text-[10px] border-primary/30 text-primary">
                        &sect; {cit.section}
                      </Badge>
                    </div>
                    {cit.sourceUrl && (
                      <a
                        href={cit.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-muted-foreground hover:text-primary flex items-center gap-1 transition-colors"
                      >
                        <span>Official Bulletin</span>
                        <ArrowSquareOut className="size-3" />
                      </a>
                    )}
                  </div>

                  <div className="p-3 rounded-md bg-secondary/60 border border-border/70 text-foreground text-sm leading-relaxed">
                    &ldquo;{cit.rebuttalBullet}&rdquo;
                  </div>

                  <div className="text-xs text-muted-foreground leading-relaxed pt-1">
                    <strong className="text-foreground">Patient Chart Evidence:</strong> {cit.criteriaMetText}
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* Phase 3: Insurer Disqualification Trap Counters */}
          <Card className="rounded-xl border border-border/80 bg-card/75 backdrop-blur-xl p-4 space-y-3 shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                  Phase 3 &bull; 2:00 - 2:45
                </span>
                <h2 className="text-sm font-semibold text-foreground font-sans">
                  Insurer Trap Questions & Direct Verbal Rebuttals
                </h2>
              </div>
              <Badge variant="outline" className="text-[10px] border-destructive/40 text-destructive">
                {script.disqualificationCounters.length} Trap Counters
              </Badge>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {script.disqualificationCounters.map((trap, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-lg border border-border/70 bg-card/50 space-y-2.5 flex flex-col justify-between"
                >
                  <div className="space-y-2">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-1.5 text-destructive font-semibold text-xs">
                        <WarningCircle className="size-3.5 shrink-0" />
                        <span>Insurer Trap #{idx + 1}</span>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleCopy(trap.physicianDirectRebuttal, `trap-${idx}`)}
                        className="h-6 text-[10px] px-1.5 text-muted-foreground hover:text-foreground cursor-pointer gap-1"
                      >
                        {copiedSection === `trap-${idx}` ? (
                          <Check className="size-3 text-emerald-400" />
                        ) : (
                          <Copy className="size-3" />
                        )}
                        <span>{copiedSection === `trap-${idx}` ? "Copied" : "Copy"}</span>
                      </Button>
                    </div>

                    <div className="text-xs font-medium text-foreground/90 bg-destructive/10 border border-destructive/25 p-2.5 rounded-md leading-relaxed">
                      &ldquo;{trap.insurerTrapQuestion}&rdquo;
                    </div>

                    <div className="space-y-1">
                      <div className="text-[10px] font-mono text-primary font-bold uppercase tracking-wider">
                        Physician Verbal Counter:
                      </div>
                      <div className="text-xs text-foreground bg-secondary/70 border border-border/70 p-2.5 rounded-md leading-relaxed font-medium">
                        &ldquo;{trap.physicianDirectRebuttal}&rdquo;
                      </div>
                    </div>
                  </div>

                  <div className="pt-2 border-t border-border/40 space-y-1 text-xs text-muted-foreground leading-relaxed">
                    <div>
                      <strong className="text-foreground">Clinical Rationale:</strong> {trap.clinicalRationale}
                    </div>
                    {trap.regulatoryLeverage && (
                      <div className="text-primary font-medium">
                        <strong>Regulatory Leverage:</strong> {trap.regulatoryLeverage}
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* Phase 4: State Bad-Faith Demand Card */}
          <Card className="rounded-xl border border-border/80 bg-card/75 backdrop-blur-xl p-4 space-y-3 shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                  Phase 4 &bull; 2:45 - 3:30
                </span>
                <h2 className="text-sm font-semibold text-foreground font-sans">
                  Closing Salvo & Written Determination Demand
                </h2>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleCopy(script.statutoryDemands, "p4")}
                className="h-7 text-xs px-2 text-muted-foreground hover:text-foreground cursor-pointer gap-1"
              >
                {copiedSection === "p4" ? (
                  <Check className="size-3 text-emerald-400" />
                ) : (
                  <Copy className="size-3" />
                )}
                <span>{copiedSection === "p4" ? "Copied" : "Copy"}</span>
              </Button>
            </div>

            <p className="text-xs text-muted-foreground leading-relaxed">
              Deliver firmly before hanging up if the medical director indicates reluctance to overturn the denial immediately:
            </p>

            <div className="p-3.5 rounded-lg bg-destructive/10 border border-destructive/30 text-foreground text-sm leading-relaxed">
              &ldquo;{script.statutoryDemands}&rdquo;
            </div>

            <div className="flex items-center gap-2 text-xs text-muted-foreground leading-relaxed">
              <Scales className="size-4 text-primary shrink-0" />
              <span>
                Demanding immediate written rationale under state bad-faith timelines causes over 60% of peer-to-peer denials to be reversed on the call.
              </span>
            </div>
          </Card>
        </div>
      )}

      {/* MODE 2: LIVE CALL COPILOT (Real-Time Voice Defense & AI Practice) */}
      {activeMode === "copilot" && (
        <P2PLiveCopilot claim={claim} />
      )}

      {/* Strategy Customization Modal */}
      <Dialog open={isCustomizeOpen} onOpenChange={setIsCustomizeOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-base font-bold text-foreground">
              <Sliders className="size-4 text-primary" />
              <span>Customize P2P Defense Strategy</span>
            </DialogTitle>
            <DialogDescription className="text-xs text-muted-foreground">
              Adjust physician credentials, reviewer specialty assumptions, and strategic focus for Claim #{claim.claimNumber}.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3 py-2 text-xs font-sans">
            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Treating Physician Name
              </label>
              <Input
                value={customPhysicianName}
                onChange={(e) => setCustomPhysicianName(e.target.value)}
                placeholder="e.g. Dr. Amanda Vance, MD"
                className="h-8 text-xs font-sans"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Physician Board Specialty / Subspecialty
              </label>
              <Input
                value={customPhysicianSpecialty}
                onChange={(e) => setCustomPhysicianSpecialty(e.target.value)}
                placeholder="e.g. Board-Certified Orthopedic Spine Surgeon"
                className="h-8 text-xs font-sans"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Payer Medical Director Role
              </label>
              <Input
                value={customMedicalDirectorRole}
                onChange={(e) => setCustomMedicalDirectorRole(e.target.value)}
                placeholder="e.g. Insurer Medical Director / Peer Reviewer"
                className="h-8 text-xs font-sans"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Custom Tactical Notes / Case Emphasis
              </label>
              <textarea
                value={customStrategyNotes}
                onChange={(e) => setCustomStrategyNotes(e.target.value)}
                rows={3}
                placeholder="e.g. Emphasize MRI disc herniation millimeter grade, failure of 8 weeks PT, and progressive motor deficit."
                className="w-full text-xs p-2 rounded-md bg-secondary/50 border border-border/80 text-foreground focus:outline-none focus:ring-1 focus:ring-primary leading-relaxed resize-none font-sans"
              />
            </div>
          </div>

          <DialogFooter className="gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsCustomizeOpen(false)}
              className="text-xs h-8 cursor-pointer"
            >
              Cancel
            </Button>
            <Button
              size="sm"
              onClick={() => {
                setIsCustomizeOpen(false);
                generateScript({
                  physicianName: customPhysicianName || undefined,
                  physicianSpecialty: customPhysicianSpecialty || undefined,
                  medicalDirectorRole: customMedicalDirectorRole || undefined,
                  customStrategyNotes: customStrategyNotes || undefined,
                });
              }}
              className="text-xs h-8 bg-primary text-primary-foreground hover:bg-primary/90 cursor-pointer"
            >
              Apply & Re-Synthesize
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};
