import React, { useState, useEffect, useRef } from "react";
import { Claim } from "../../types";
import { useP2PDefense } from "../../hooks/useP2PDefense";
import { NavigationView } from "../layout/Sidebar";
import { SentinelFlowStepper } from "../common/SentinelFlowStepper";
import { Card } from "../ui/card";
import { P2PLiveCopilot } from "./P2PLiveCopilot";
import {
  PhoneCall,
  Play,
  Pause,
  ArrowCounterClockwise,
  Printer,
  Copy,
  Check,
  Sparkle,
  ShieldWarning,
  ShieldCheck,
  Scales,
  WarningCircle,
  FileText,
  Sliders,
  Stethoscope,
  CircleNotch,
  ArrowSquareOut,
  X,
  CaretRight,
} from "@phosphor-icons/react";
import { Button } from "../ui/button";
import { Badge } from "../ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../ui/dialog";
import { Input } from "../ui/input";
import { formatCurrency } from "../../lib/utils";
import { cn } from "../../lib/utils";

interface P2PDefenseStudioProps {
  claim: Claim;
  onNavigateView?: (view: NavigationView) => void;
}

export const P2PDefenseStudio: React.FC<P2PDefenseStudioProps> = ({
  claim,
  onNavigateView,
}) => {
  const {
    script,
    isLoadingScript,
    markdownContent,
    setMarkdownContent,
    isSynthesizing,
    saveStatus,
    generateScript,
    isTimerRunning,
    timerSeconds,
    activePhaseIndex,
    startTimer,
    pauseTimer,
    resetTimer,
  } = useP2PDefense(claim);

  const [activeTab, setActiveTab] = useState<"copilot" | "script" | "cheatsheet" | "raw">("copilot");
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [isCustomizeOpen, setIsCustomizeOpen] = useState<boolean>(false);
  const [checkedChecklist, setCheckedChecklist] = useState<Record<number, boolean>>({});

  // Customization Form state
  const [customPhysicianName, setCustomPhysicianName] = useState<string>(
    claim.appealContext?.sender?.name || claim.providerName || ""
  );
  const [customPhysicianSpecialty, setCustomPhysicianSpecialty] = useState<string>(
    claim.appealContext?.sender?.credentials || "Board-Certified Treating Specialist"
  );
  const [customMedicalDirectorRole, setCustomMedicalDirectorRole] = useState<string>(
    "Insurer Medical Director / Utilization Reviewer"
  );
  const [customStrategyNotes, setCustomStrategyNotes] = useState<string>("");

  const phase0Ref = useRef<HTMLDivElement | null>(null);
  const phase1Ref = useRef<HTMLDivElement | null>(null);
  const phase2Ref = useRef<HTMLDivElement | null>(null);
  const phase3Ref = useRef<HTMLDivElement | null>(null);

  // Auto-generate script on initial mount if none exists for this claim
  const hasAutoGeneratedRef = useRef<boolean>(false);
  useEffect(() => {
    if (!isLoadingScript && !script && !isSynthesizing && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      generateScript({
        physicianName: customPhysicianName || undefined,
        physicianSpecialty: customPhysicianSpecialty || undefined,
        medicalDirectorRole: customMedicalDirectorRole || undefined,
      }).catch((err) => {
        console.error("Auto-generate P2P script failed:", err);
      });
    }
  }, [isLoadingScript, script, isSynthesizing, generateScript, customPhysicianName, customPhysicianSpecialty, customMedicalDirectorRole]);

  // Copy helper
  const handleCopy = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => {
      setCopiedSection(null);
    }, 2000);
  };

  const handlePrint = () => {
    if (!script) {
      window.print();
      return;
    }

    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      window.print();
      return;
    }

    printWindow.opener = null;

    const styles = Array.from(document.querySelectorAll("link[rel='stylesheet'], style"))
      .map((style) => style.outerHTML)
      .join("\n");

    const rapidChecklistHtml = (script.condensedCheatSheet?.rapidChecklist || [])
      .map(
        (item) => `
        <div style="display:flex;align-items:flex-start;gap:8px;padding:6px 8px;border:1px solid #cbd5e1;border-radius:6px;font-size:11px;">
          <div style="width:12px;height:12px;border:1.5px solid #64748b;border-radius:3px;margin-top:1px;flex-shrink:0;"></div>
          <span>${item}</span>
        </div>`
      )
      .join("");

    const mustSayHtml = (script.condensedCheatSheet?.mustSayPoints || [])
      .map(
        (pt) => `
        <li style="margin-bottom:6px;line-height:1.4;">
          <strong>•</strong> ${pt}
        </li>`
      )
      .join("");

    const doNotConcedeHtml = (script.condensedCheatSheet?.doNotConcedePoints || [])
      .map(
        (pt) => `
        <li style="margin-bottom:6px;line-height:1.4;color:#991b1b;">
          <strong>✕</strong> ${pt}
        </li>`
      )
      .join("");

    const disqualificationHtml = (script.disqualificationCounters || [])
      .slice(0, 3)
      .map(
        (trap) => `
        <div style="margin-bottom:8px;padding:8px;border:1px solid #e2e8f0;border-radius:6px;font-size:11px;">
          <div style="font-weight:bold;color:#b91c1c;margin-bottom:4px;">Insurer Trap: &ldquo;${trap.insurerTrapQuestion}&rdquo;</div>
          <div style="background:#f8fafc;padding:6px;border-radius:4px;border-left:3px solid #0284c7;color:#0f172a;">&ldquo;${trap.physicianDirectRebuttal}&rdquo;</div>
        </div>`
      )
      .join("");

    const cheatSheetHtml = `
      <div class="printable-p2p-cheatsheet" style="max-width:800px;margin:0 auto;padding:12mm 15mm;font-family:Arial,Helvetica,sans-serif;color:#0f172a;background:#fff;">
        <div style="border-bottom:2px solid #0284c7;padding-bottom:8px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:flex-end;">
          <div>
            <div style="font-size:9px;font-family:monospace;letter-spacing:1.5px;color:#0284c7;font-weight:bold;text-transform:uppercase;">
              ClaimHero Clinical Sentinel • Rapid P2P Pocket Guide
            </div>
            <h1 style="margin:2px 0 0 0;font-size:18px;font-weight:bold;color:#020617;">
              Peer-to-Peer Defense Cheat Sheet
            </h1>
          </div>
          <div style="text-align:right;font-size:11px;font-family:monospace;">
            <div style="font-weight:bold;color:#0f172a;">Claim #${claim.claimNumber}</div>
            <div style="color:#64748b;">${payer} • ${formatCurrency(claim.deniedAmount)}</div>
          </div>
        </div>

        <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;font-size:11px;font-family:monospace;padding:8px;background:#f1f5f9;border:1px solid #cbd5e1;border-radius:6px;margin-bottom:12px;">
          <div><span style="color:#64748b;font-size:9px;display:block;">PATIENT:</span><strong>${claim.patient?.name || "Patient"}</strong></div>
          <div><span style="color:#64748b;font-size:9px;display:block;">MEMBER ID:</span><strong>${claim.patient?.memberId || "N/A"}</strong></div>
          <div><span style="color:#64748b;font-size:9px;display:block;">CPT CODES:</span><strong style="color:#0369a1;">${cptList}</strong></div>
          <div><span style="color:#64748b;font-size:9px;display:block;">ICD-10:</span><strong style="color:#0369a1;">${icdList}</strong></div>
        </div>

        <div style="margin-bottom:12px;">
          <div style="font-size:11px;font-weight:bold;text-transform:uppercase;color:#0f172a;margin-bottom:6px;">
            Pre-Flight Call Checklist
          </div>
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">
            ${rapidChecklistHtml}
          </div>
        </div>

        <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;">
          <div style="padding:10px;border:1px solid #bae6fd;background:#f0f9ff;border-radius:6px;">
            <div style="font-size:11px;font-weight:bold;color:#0369a1;text-transform:uppercase;margin-bottom:6px;">
              Key Must-Say Points
            </div>
            <ul style="margin:0;padding-left:14px;font-size:11px;color:#0f172a;">
              ${mustSayHtml}
            </ul>
          </div>

          <div style="padding:10px;border:1px solid #fecaca;background:#fef2f2;border-radius:6px;">
            <div style="font-size:11px;font-weight:bold;color:#b91c1c;text-transform:uppercase;margin-bottom:6px;">
              Do NOT Concede Red Flags
            </div>
            <ul style="margin:0;padding-left:14px;font-size:11px;color:#0f172a;">
              ${doNotConcedeHtml}
            </ul>
          </div>
        </div>

        <div style="margin-bottom:12px;">
          <div style="font-size:11px;font-weight:bold;text-transform:uppercase;color:#0f172a;margin-bottom:6px;">
            Rapid Disqualification Counters
          </div>
          ${disqualificationHtml}
        </div>

        <div style="padding:10px;border:1px solid #fed7aa;background:#fffbeb;border-radius:6px;font-size:11px;">
          <div style="font-weight:bold;color:#b45309;text-transform:uppercase;margin-bottom:4px;">Closing Demand Statement:</div>
          <div style="font-style:italic;color:#1e293b;">&ldquo;${script.condensedCheatSheet?.closingDemandStatement || script.statutoryDemands || ""}&rdquo;</div>
        </div>
      </div>
    `;

    printWindow.document.open();
    printWindow.document.write(`<!doctype html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <title>P2P Defense Cheat Sheet - Claim #${claim.claimNumber}</title>
          ${styles}
          <style>
            @page { size: letter portrait; margin: 0; }
            html, body { margin: 0; background: #fff; color: #0f172a; font-family: Arial, Helvetica, sans-serif; }
            .printable-p2p-cheatsheet { box-shadow: none !important; }
          </style>
        </head>
        <body>
          ${cheatSheetHtml}
        </body>
      </html>`);
    printWindow.document.close();
    printWindow.focus();
    printWindow.onafterprint = () => printWindow.close();
    window.setTimeout(() => printWindow.print(), 250);
  };

  // Format seconds to mm:ss
  const formatTimer = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  const timerPercent = Math.min(100, Math.round((timerSeconds / 180) * 100));

  const payer = claim.patient?.insurancePayer || "Health Insurer";
  const cptList = (claim.cptCodes || []).join(", ");
  const icdList = (claim.icd10Codes || []).join(", ");

  const phases = [
    { label: "Phase 1: Opening", time: "0:00 - 0:45", ref: phase0Ref },
    { label: "Phase 2: CPB Policies", time: "0:45 - 2:00", ref: phase1Ref },
    { label: "Phase 3: Trap Counters", time: "2:00 - 2:45", ref: phase2Ref },
    { label: "Phase 4: Bad-Faith Demand", time: "2:45 - 3:30", ref: phase3Ref },
  ];

  const handleJumpToPhase = (index: number) => {
    const targetRef = phases[index]?.ref?.current;
    if (targetRef) {
      targetRef.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  const toggleChecklistItem = (idx: number) => {
    setCheckedChecklist((prev: Record<number, boolean>) => ({
      ...prev,
      [idx]: !prev[idx],
    }));
  };

  return (
    <div className="space-y-3 animate-fadeIn pb-20 mb-8 min-h-[calc(100vh-6.5rem)] flex flex-col">
      {/* 4-Step Guided Sentinel Stepper */}
      <SentinelFlowStepper
        claim={claim}
        currentView="p2p"
        onNavigateView={(v) => {
          if (onNavigateView) onNavigateView(v as NavigationView);
        }}
        evidencesCount={script?.clinicalPolicyCitations?.length || 0}
        hasDraftedBrief={Boolean(script)}
        isProcessing={isSynthesizing}
        processingLabel="Synthesizing P2P Verbal Defense..."
      />

      {/* Studio Header Toolbar Card */}
      <Card className="p-3.5 shrink-0 overflow-visible no-print">
        <div className="flex flex-col 2xl:flex-row 2xl:items-center justify-between gap-3">
          {/* Left: Case Info */}
          <div className="flex items-center gap-3 min-w-0">
            <div className="flex size-9 items-center justify-center rounded-md bg-primary text-primary-foreground shrink-0 shadow-xs">
              <PhoneCall className="size-4.5" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <h2 className="text-sm font-semibold text-foreground font-sans truncate">
                  Physician Peer-to-Peer (P2P) Defense Tele-Script
                </h2>
                <Badge variant="outline" className="font-mono text-[10px]">
                  Claim #{claim.claimNumber}
                </Badge>
                {saveStatus === "saving" && (
                  <span className="flex items-center gap-1 text-[11px] font-mono text-muted-foreground animate-pulse">
                    <CircleNotch className="size-3 animate-spin" />
                    <span>Saving...</span>
                  </span>
                )}
                {saveStatus === "saved" && (
                  <span className="flex items-center gap-1 text-[11px] font-mono text-emerald-600 dark:text-emerald-400">
                    <Check className="size-3" />
                    <span>Synced</span>
                  </span>
                )}
              </div>
              <p className="text-xs text-muted-foreground truncate">
                Patient: <span className="text-foreground font-medium">{claim.patient?.name || "Insured Patient"}</span> • Payer:{" "}
                <span className="text-foreground font-medium">{payer}</span> • Disputed:{" "}
                <span className="text-foreground font-medium">{formatCurrency(claim.deniedAmount)}</span>
              </p>
            </div>
          </div>

          {/* Right: Actions Toolbar matching Image 1 */}
          <div className="flex items-center gap-2 flex-wrap 2xl:flex-nowrap shrink-0">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsCustomizeOpen(true)}
              className="h-8 rounded-md px-2.5 text-xs gap-1.5 shrink-0 border-border/70"
            >
              <Sliders className="size-3.5" />
              <span>Customize</span>
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={() =>
                handleCopy(
                  activeTab === "cheatsheet" && script?.condensedCheatSheet
                    ? JSON.stringify(script.condensedCheatSheet, null, 2)
                    : script?.fullScriptMarkdown || markdownContent,
                  "all"
                )
              }
              className="h-8 rounded-md px-2.5 text-xs gap-1.5 shrink-0 border-border/70"
            >
              {copiedSection === "all" ? (
                <Check className="size-3.5 text-emerald-400" />
              ) : (
                <Copy className="size-3.5" />
              )}
              <span>{copiedSection === "all" ? "Copied All" : "Copy Script"}</span>
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="h-8 rounded-md px-2.5 text-xs gap-1.5 shrink-0 border-border/70 text-foreground"
              title="Print high-contrast single sheet for physical clinic clipboard"
            >
              <Printer className="size-3.5" />
              <span>Print Cheat Sheet</span>
            </Button>

            <Button
              size="sm"
              onClick={() =>
                generateScript({
                  physicianName: customPhysicianName || undefined,
                  physicianSpecialty: customPhysicianSpecialty || undefined,
                  medicalDirectorRole: customMedicalDirectorRole || undefined,
                  customStrategyNotes: customStrategyNotes || undefined,
                })
              }
              disabled={isSynthesizing}
              className="h-8 rounded-md px-3 text-xs font-semibold gap-1.5 bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs shrink-0 cursor-pointer"
            >
              {isSynthesizing ? (
                <CircleNotch className="size-3.5 animate-spin" />
              ) : (
                <Sparkle className="size-3.5" />
              )}
              <span>{isSynthesizing ? "Synthesizing Defense..." : "Re-Synthesize"}</span>
            </Button>
          </div>
        </div>

        {/* Live 3-Minute Verbal Stopwatch / Pacer HUD */}
        <div className="rounded-lg border border-border/80 bg-secondary/20 p-2.5 space-y-2 mt-3">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
            {/* Timer Controls & Time display */}
            <div className="flex items-center gap-2 shrink-0">
              <Button
                variant={isTimerRunning ? "destructive" : "default"}
                size="sm"
                onClick={isTimerRunning ? pauseTimer : startTimer}
                className={cn(
                  "h-8 px-3 rounded-md text-xs font-semibold gap-1.5 transition-all shadow-xs cursor-pointer",
                  isTimerRunning
                    ? "bg-destructive text-destructive-foreground hover:bg-destructive/90 animate-pulse"
                    : "bg-emerald-600 hover:bg-emerald-500 text-white"
                )}
              >
                {isTimerRunning ? (
                  <>
                    <Pause className="size-3.5" />
                    <span>Pause Call</span>
                  </>
                ) : (
                  <>
                    <Play className="size-3.5" />
                    <span>{timerSeconds > 0 ? "Resume Call" : "Start Live Call (3:00)"}</span>
                  </>
                )}
              </Button>

              <Button
                variant="outline"
                size="icon"
                onClick={resetTimer}
                disabled={timerSeconds === 0}
                className="size-8 rounded-md shrink-0 border-border/70 text-muted-foreground hover:text-foreground cursor-pointer"
                title="Reset Timer"
              >
                <ArrowCounterClockwise className="size-3.5" />
              </Button>

              <div className="flex items-center gap-1 font-mono text-xs bg-background/80 px-2 py-1 rounded-md border border-border/60">
                <span className="font-bold text-foreground tracking-wider">{formatTimer(timerSeconds)}</span>
                <span className="text-muted-foreground">/ 03:00</span>
              </div>
            </div>

            {/* Phase Navigation Pills */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-1.5 flex-1 max-w-2xl">
              {phases.map((p, idx) => {
                const isActive = isTimerRunning && activePhaseIndex === idx;
                const isPassed = timerSeconds > (idx === 0 ? 45 : idx === 1 ? 120 : idx === 2 ? 165 : 180);
                return (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => handleJumpToPhase(idx)}
                    className={cn(
                      "h-8 px-2 py-1 rounded-md text-left transition-all border text-[11px] font-sans flex items-center justify-between gap-1 truncate cursor-pointer",
                      isActive
                        ? "border-primary bg-primary/20 text-primary font-semibold ring-1 ring-primary/40 shadow-xs"
                        : isPassed
                        ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400 font-normal"
                        : "border-border/60 bg-card/40 text-muted-foreground hover:bg-card/80 hover:text-foreground"
                    )}
                  >
                    <span className="truncate">{p.label}</span>
                    <span className="font-mono text-[9px] opacity-70 shrink-0">{p.time}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Visual Call Progress Bar */}
          <div className="w-full bg-secondary/80 h-1.5 rounded-full overflow-hidden">
            <div
              className={cn(
                "h-full transition-all duration-300 rounded-full",
                timerPercent >= 100 ? "bg-destructive" : "bg-primary"
              )}
              style={{ width: `${timerPercent}%` }}
            />
          </div>
        </div>

        {/* View Switcher Tabs */}
        <div className="flex items-center justify-between border-t border-border/50 pt-2.5 mt-3">
          <div className="flex items-center gap-1.5 flex-wrap">
            <button
              onClick={() => setActiveTab("copilot")}
              className={cn(
                "px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer flex items-center gap-1.5",
                activeTab === "copilot"
                  ? "bg-primary text-primary-foreground font-semibold shadow-xs"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/60"
              )}
            >
              <span>Live Call Copilot</span>
              <Badge
                variant="outline"
                className={cn(
                  "text-[9px] px-1 py-0 h-4 uppercase font-mono",
                  activeTab === "copilot"
                    ? "border-white/40 text-white bg-white/10"
                    : "border-primary/40 text-primary"
                )}
              >
                Live AI
              </Badge>
            </button>
            <button
              onClick={() => setActiveTab("script")}
              className={cn(
                "px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer",
                activeTab === "script"
                  ? "bg-secondary text-foreground font-semibold shadow-xs"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/60"
              )}
            >
              Full Verbal Tele-Script
            </button>
            <button
              onClick={() => setActiveTab("cheatsheet")}
              className={cn(
                "px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer flex items-center gap-1.5",
                activeTab === "cheatsheet"
                  ? "bg-secondary text-foreground font-semibold shadow-xs"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/60"
              )}
            >
              <span>Pocket Clinic Cheat Sheet</span>
              <Badge variant="outline" className="text-[9px] px-1 py-0 h-4 border-primary/30 text-primary">
                Print / Mobile
              </Badge>
            </button>
            <button
              onClick={() => setActiveTab("raw")}
              className={cn(
                "px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer",
                activeTab === "raw"
                  ? "bg-secondary text-foreground font-semibold shadow-xs"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/60"
              )}
            >
              Raw Markdown
            </button>
          </div>

          <div className="text-xs font-mono text-muted-foreground hidden sm:block">
            Denial Reason: <span className="text-foreground font-medium">{claim.denialReasonCode || "CO-50"}</span>
          </div>
        </div>
      </Card>

      {/* TAB 0: REAL-TIME LIVE CALL COPILOT */}
      {activeTab === "copilot" && <P2PLiveCopilot claim={claim} />}

      {/* Loading Skeleton */}
      {isSynthesizing && !script && activeTab !== "copilot" && (
        <div className="rounded-xl border border-border/60 bg-card/60 backdrop-blur-md p-8 flex flex-col items-center justify-center space-y-3">
          <CircleNotch className="size-6 text-primary animate-spin" />
          <div className="text-xs font-mono text-muted-foreground">
            Extracting CPB criteria & synthesizing 3-minute P2P verbal defense...
          </div>
        </div>
      )}

      {/* Main Workspace Body */}
      {script && (
        <>
          {/* TAB 1: FULL VERBAL TELE-SCRIPT */}
          {activeTab === "script" && (
            <div className="space-y-4 no-print">
              {/* Phase 1: Statutory Opening Card */}
              <div
                ref={phase0Ref}
                className={cn(
                  "rounded-xl border bg-card/75 backdrop-blur-md p-4 transition-all space-y-3 shadow-xs",
                  activePhaseIndex === 0 && isTimerRunning
                    ? "border-primary ring-1 ring-primary/40 bg-card/90"
                    : "border-border/70"
                )}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                      0:00 - 0:45
                    </span>
                    <h2 className="text-sm font-semibold text-foreground font-sans">
                      Phase 1: Statutory Opening & Reviewer Credential Inquest
                    </h2>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Badge variant="outline" className="text-[10px] font-sans border-muted-foreground/30 text-muted-foreground">
                      Cadence: Assertive & Firm
                    </Badge>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopy(script.openingStatutoryStatement, "p1")}
                      className="h-7 text-xs px-2 text-muted-foreground hover:text-foreground"
                    >
                      {copiedSection === "p1" ? (
                        <Check className="size-3 text-emerald-400" />
                      ) : (
                        <Copy className="size-3" />
                      )}
                    </Button>
                  </div>
                </div>

                <p className="text-xs text-muted-foreground leading-relaxed font-sans">
                  Read directly upon line connection to establish legal footing under ERISA 29 CFR § 2560.503-1 and state utilization review laws:
                </p>

                <div className="p-3.5 rounded-lg bg-secondary/50 border border-border/80 text-foreground font-sans text-sm leading-relaxed tracking-normal selection:bg-primary/20">
                  {script.openingStatutoryStatement}
                </div>

                <div className="flex items-center gap-2 text-xs font-sans text-amber-500/95 dark:text-amber-400/95 bg-amber-500/10 border border-amber-500/20 px-3 py-2 rounded-md leading-relaxed">
                  <ShieldWarning className="size-4 shrink-0" />
                  <span>
                    <strong className="font-semibold">Tactical Note:</strong> If the reviewer admits they are not board-certified in this exact specialty, note their name immediately for state same-specialty appeal complaints.
                  </span>
                </div>
              </div>

              {/* Phase 2: CPB Section Citations & Clinical Defense */}
              <div
                ref={phase1Ref}
                className={cn(
                  "rounded-xl border bg-card/75 backdrop-blur-md p-4 transition-all space-y-3 shadow-xs",
                  activePhaseIndex === 1 && isTimerRunning
                    ? "border-primary ring-1 ring-primary/40 bg-card/90"
                    : "border-border/70"
                )}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                      0:45 - 2:00
                    </span>
                    <h2 className="text-sm font-semibold text-foreground font-sans">
                      Phase 2: Exact Policy Section Citations & Clinical Counter-Offensive
                    </h2>
                  </div>
                  <Badge variant="outline" className="text-[10px] font-sans border-muted-foreground/30 text-muted-foreground">
                    Cadence: Objective & Evidentiary
                  </Badge>
                </div>

                <p className="text-xs text-muted-foreground leading-relaxed font-sans">
                  Cite the exact insurer clinical policy bulletin sections and prove criteria fulfillment from patient chart records:
                </p>

                <div className="grid grid-cols-1 gap-3">
                  {script.clinicalPolicyCitations.map((cit, idx) => (
                    <div
                      key={idx}
                      className="p-3.5 rounded-lg border border-border/70 bg-card/50 space-y-2.5 text-xs font-sans"
                    >
                      <div className="flex items-center justify-between flex-wrap gap-1">
                        <div className="flex items-center gap-2">
                          <span className="font-mono font-bold text-primary">
                            Point {idx + 1}:
                          </span>
                          <span className="font-semibold text-foreground">
                            {cit.cpbTitle}
                          </span>
                          <Badge variant="outline" className="font-mono text-[10px] border-primary/30 text-primary">
                            § {cit.section}
                          </Badge>
                        </div>
                        {cit.sourceUrl && (
                          <a
                            href={cit.sourceUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-xs font-sans text-muted-foreground hover:text-primary flex items-center gap-1 transition-colors"
                          >
                            <span>Official Source</span>
                            <ArrowSquareOut className="size-3" />
                          </a>
                        )}
                      </div>

                      <div className="p-3 rounded-md bg-secondary/60 border border-border/70 text-foreground font-sans text-sm leading-relaxed">
                        &ldquo;{cit.rebuttalBullet}&rdquo;
                      </div>

                      <div className="text-xs text-muted-foreground leading-relaxed font-sans">
                        <strong className="text-foreground font-semibold">Chart Verification:</strong> {cit.criteriaMetText}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Phase 3: Disqualification Trap Matrix */}
              <div
                ref={phase2Ref}
                className={cn(
                  "rounded-xl border bg-card/75 backdrop-blur-md p-4 transition-all space-y-3 shadow-xs",
                  activePhaseIndex === 2 && isTimerRunning
                    ? "border-primary ring-1 ring-primary/40 bg-card/90"
                    : "border-border/70"
                )}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                      2:00 - 2:45
                    </span>
                    <h2 className="text-sm font-semibold text-foreground font-sans">
                      Phase 3: Insurer Disqualification Trap Counters
                    </h2>
                  </div>
                  <Badge variant="outline" className="text-[10px] font-sans border-destructive/40 text-destructive">
                    Direct Counters ({script.disqualificationCounters.length})
                  </Badge>
                </div>

                <p className="text-xs text-muted-foreground leading-relaxed font-sans">
                  When the medical director deploys common denial disqualifiers, respond immediately with these targeted verbal counter-strikes:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {script.disqualificationCounters.map((trap, idx) => (
                    <div
                      key={idx}
                      className="p-3.5 rounded-lg border border-border/70 bg-card/50 space-y-2.5 flex flex-col justify-between font-sans"
                    >
                      <div className="space-y-2">
                        <div className="flex items-start justify-between gap-2">
                          <div className="flex items-center gap-1.5 text-destructive font-semibold text-xs">
                            <WarningCircle className="size-3.5 shrink-0" />
                            <span>Insurer Trap #{idx + 1}</span>
                          </div>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleCopy(trap.physicianDirectRebuttal, `trap-${idx}`)}
                            className="h-6 text-[10px] px-1.5 text-muted-foreground hover:text-foreground"
                          >
                            {copiedSection === `trap-${idx}` ? (
                              <Check className="size-3 text-emerald-400" />
                            ) : (
                              <Copy className="size-3" />
                            )}
                          </Button>
                        </div>

                        <div className="text-xs font-medium text-foreground/90 bg-destructive/10 border border-destructive/25 p-2.5 rounded-md leading-relaxed font-sans">
                          &ldquo;{trap.insurerTrapQuestion}&rdquo;
                        </div>

                        <div className="space-y-1">
                          <div className="text-[11px] font-sans text-primary font-bold uppercase tracking-wide">
                            Physician Verbal Counter:
                          </div>
                          <div className="text-xs font-sans text-foreground/95 bg-secondary/70 border border-border/70 p-3 rounded-md leading-relaxed font-medium">
                            &ldquo;{trap.physicianDirectRebuttal}&rdquo;
                          </div>
                        </div>
                      </div>

                      <div className="pt-2.5 border-t border-border/40 space-y-1 text-xs text-muted-foreground font-sans leading-relaxed">
                        <div>
                          <strong className="text-foreground font-semibold">Clinical Rationale:</strong> {trap.clinicalRationale}
                        </div>
                        {trap.regulatoryLeverage && (
                          <div className="text-primary/95">
                            <strong className="font-semibold">Regulatory Leverage:</strong> {trap.regulatoryLeverage}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Phase 4: State Bad-Faith Demand Card */}
              <div
                ref={phase3Ref}
                className={cn(
                  "rounded-xl border bg-card/75 backdrop-blur-md p-4 transition-all space-y-3 shadow-xs",
                  activePhaseIndex === 3 && isTimerRunning
                    ? "border-primary ring-1 ring-primary/40 bg-card/90"
                    : "border-border/70"
                )}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-primary px-1.5 py-0.5 rounded bg-primary/10 border border-primary/20">
                      2:45 - 3:30
                    </span>
                    <h2 className="text-sm font-semibold text-foreground font-sans">
                      Phase 4: State Bad-Faith Warning & Written Denial Demand
                    </h2>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Badge variant="outline" className="text-[10px] font-sans border-destructive/40 text-destructive">
                      Closing Salvo
                    </Badge>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopy(script.statutoryDemands, "p4")}
                      className="h-7 text-xs px-2 text-muted-foreground hover:text-foreground"
                    >
                      {copiedSection === "p4" ? (
                        <Check className="size-3 text-emerald-400" />
                      ) : (
                        <Copy className="size-3" />
                      )}
                    </Button>
                  </div>
                </div>

                <p className="text-xs text-muted-foreground leading-relaxed font-sans">
                  Deliver firmly before hanging up if the medical director indicates reluctance to overturn the denial immediately:
                </p>

                <div className="p-3.5 rounded-lg bg-destructive/10 border border-destructive/30 text-foreground font-sans text-sm leading-relaxed tracking-normal font-normal">
                  {script.statutoryDemands}
                </div>

                <div className="flex items-center gap-2 text-xs font-sans text-muted-foreground leading-relaxed">
                  <Scales className="size-4 text-primary shrink-0" />
                  <span>
                    Invoking reviewer license credentials and state bad-faith timelines causes over 60% of peer-to-peer denials to be reversed on the call.
                  </span>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: POCKET CLINIC CHEAT SHEET (Print & Mobile Optimized) */}
          {activeTab === "cheatsheet" && (
            <div className="printable-p2p-cheatsheet rounded-xl border border-border/80 bg-card/85 backdrop-blur-xl p-5 space-y-5 shadow-sm font-sans">
              {/* Header Box */}
              <div className="border-b-2 border-primary/40 pb-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <div className="text-[10px] font-mono uppercase tracking-widest text-primary font-bold">
                    ClaimHero Clinical Sentinel • Rapid P2P Pocket Guide
                  </div>
                  <h2 className="text-lg font-bold text-foreground">
                    Peer-to-Peer Defense Cheat Sheet
                  </h2>
                </div>
                <div className="text-right text-xs font-mono">
                  <div className="font-bold text-foreground">
                    Claim #{claim.claimNumber}
                  </div>
                  <div className="text-muted-foreground">
                    {payer} • {formatCurrency(claim.deniedAmount)}
                  </div>
                </div>
              </div>

              {/* Case Identification Strip */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono p-2.5 rounded-lg bg-secondary/60 border border-border/60">
                <div>
                  <span className="text-muted-foreground block text-[10px]">PATIENT:</span>
                  <span className="font-semibold text-foreground">{claim.patient?.name || "Patient"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-[10px]">MEMBER ID:</span>
                  <span className="font-semibold text-foreground">{claim.patient?.memberId || "N/A"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-[10px]">CPT CODES:</span>
                  <span className="font-semibold text-primary">{cptList}</span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-[10px]">ICD-10 CODES:</span>
                  <span className="font-semibold text-primary">{icdList}</span>
                </div>
              </div>

              {/* Pre-Flight Checklist */}
              <div className="space-y-2 font-sans">
                <div className="flex items-center justify-between">
                  <div className="text-xs font-bold font-sans uppercase tracking-wider text-foreground flex items-center gap-1.5">
                    <ShieldCheck className="size-4 text-emerald-400" />
                    <span>Pre-Flight Call Checklist</span>
                  </div>
                  <span className="text-[11px] font-sans text-muted-foreground">
                    Check off during call
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs font-sans">
                  {script.condensedCheatSheet.rapidChecklist.map((item, idx) => (
                    <button
                      key={idx}
                      onClick={() => toggleChecklistItem(idx)}
                      className={cn(
                        "flex items-start gap-2.5 p-2 rounded-md border text-left transition-colors cursor-pointer",
                        checkedChecklist[idx]
                          ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300 line-through opacity-80"
                          : "border-border/70 bg-card/60 text-foreground hover:bg-card/90"
                      )}
                    >
                      <div
                        className={cn(
                          "size-4 rounded border flex items-center justify-center shrink-0 mt-0.5 transition-colors",
                          checkedChecklist[idx]
                            ? "border-emerald-400 bg-emerald-500 text-white"
                            : "border-muted-foreground/40 bg-transparent"
                        )}
                      >
                        {checkedChecklist[idx] && <Check className="size-3" />}
                      </div>
                      <span className="leading-snug">{item}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Must-Say Points vs Do-Not-Concede Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 font-sans">
                {/* Must Say Points */}
                <div className="p-3.5 rounded-lg border border-primary/30 bg-primary/5 space-y-2">
                  <div className="text-xs font-bold font-sans uppercase tracking-wider text-primary flex items-center gap-1.5">
                    <Stethoscope className="size-4 text-primary" />
                    <span>4 Key Must-Say Points</span>
                  </div>
                  <ul className="space-y-1.5 text-xs text-foreground/95">
                    {script.condensedCheatSheet.mustSayPoints.map((pt, idx) => (
                      <li key={idx} className="flex items-start gap-2 leading-relaxed">
                        <CaretRight className="size-3 text-primary shrink-0 mt-0.5" weight="bold" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Do Not Concede */}
                <div className="p-3.5 rounded-lg border border-destructive/30 bg-destructive/5 space-y-2">
                  <div className="text-xs font-bold font-sans uppercase tracking-wider text-destructive flex items-center gap-1.5">
                    <WarningCircle className="size-4 text-destructive" />
                    <span>3 Do NOT Concede Red Flags</span>
                  </div>
                  <ul className="space-y-1.5 text-xs text-foreground/95">
                    {script.condensedCheatSheet.doNotConcedePoints.map((pt, idx) => (
                      <li key={idx} className="flex items-start gap-2 leading-relaxed">
                        <X className="size-3.5 text-destructive shrink-0 mt-0.5" weight="bold" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Rapid Disqualification Q&A Flashcards */}
              <div className="space-y-2 font-sans">
                <div className="text-xs font-bold font-sans uppercase tracking-wider text-foreground flex items-center gap-1.5">
                  <Scales className="size-4 text-primary" />
                  <span>Rapid Disqualification Counters</span>
                </div>

                <div className="space-y-2">
                  {script.disqualificationCounters.slice(0, 3).map((trap, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-lg border border-border/60 bg-card/60 flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 text-xs font-sans"
                    >
                      <div className="sm:max-w-[45%] font-medium text-destructive/90">
                        &ldquo;{trap.insurerTrapQuestion}&rdquo;
                      </div>
                      <div className="flex-1 font-sans text-foreground bg-secondary/60 p-2.5 rounded-md border border-border/50 leading-relaxed font-medium">
                        &ldquo;{trap.physicianDirectRebuttal}&rdquo;
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Closing Demand Box */}
              <div className="p-3.5 rounded-lg border border-amber-500/30 bg-amber-500/10 space-y-1.5 font-sans">
                <div className="text-xs font-sans uppercase tracking-wider text-amber-400 font-bold">
                  Closing Demand Statement:
                </div>
                <div className="text-xs font-sans text-foreground leading-relaxed font-medium">
                  &ldquo;{script.condensedCheatSheet.closingDemandStatement}&rdquo;
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: RAW SCRIPT MARKDOWN EDITOR */}
          {activeTab === "raw" && (
            <div className="no-print rounded-xl border border-border/70 bg-card/75 backdrop-blur-xl p-4 space-y-3 shadow-xs">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="size-4 text-primary" />
                  <h3 className="text-xs font-mono uppercase font-bold text-foreground">
                    Full Script Markdown Editor
                  </h3>
                </div>
                <span className="text-[10px] font-mono text-muted-foreground">
                  Edits auto-save to case record
                </span>
              </div>

              <textarea
                value={markdownContent}
                onChange={(e) => setMarkdownContent(e.target.value)}
                rows={18}
                className="w-full font-mono text-xs p-3 rounded-lg bg-secondary/50 border border-border/80 text-foreground focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary transition-all leading-relaxed resize-y"
                placeholder="Full P2P Defense Tele-Script Markdown..."
              />
            </div>
          )}
        </>
      )}

      {/* Strategy Customization Modal */}
      <Dialog open={isCustomizeOpen} onOpenChange={setIsCustomizeOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-base font-bold text-foreground">
              <Sliders className="size-4 text-primary" />
              <span>Customize P2P Defense Strategy</span>
            </DialogTitle>
            <DialogDescription className="text-xs text-muted-foreground">
              Adjust physician credentials, reviewer specialty assumptions, and strategic focus for Claim #{claim.claimNumber}.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3 py-2 text-xs">
            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Treating Physician Name
              </label>
              <Input
                value={customPhysicianName}
                onChange={(e) => setCustomPhysicianName(e.target.value)}
                placeholder="e.g. Dr. Jane Smith, MD"
                className="h-8 text-xs font-sans"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Physician Board Specialty / Subspecialty
              </label>
              <Input
                value={customPhysicianSpecialty}
                onChange={(e) => setCustomPhysicianSpecialty(e.target.value)}
                placeholder="e.g. Board-Certified Orthopedic Spine Surgeon"
                className="h-8 text-xs font-sans"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Payer Medical Director Role
              </label>
              <Input
                value={customMedicalDirectorRole}
                onChange={(e) => setCustomMedicalDirectorRole(e.target.value)}
                placeholder="e.g. Aetna Medical Director / Peer Reviewer"
                className="h-8 text-xs font-sans"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] font-mono uppercase text-muted-foreground font-semibold">
                Custom Tactical Notes / Case Emphasis
              </label>
              <textarea
                value={customStrategyNotes}
                onChange={(e) => setCustomStrategyNotes(e.target.value)}
                rows={3}
                placeholder="e.g. Emphasize MRI disc herniation millimeter grade, failure of 8 weeks PT, and progressive foot drop."
                className="w-full text-xs p-2 rounded-md bg-secondary/50 border border-border/80 text-foreground focus:outline-none focus:ring-1 focus:ring-primary leading-relaxed resize-none"
              />
            </div>
          </div>

          <DialogFooter className="gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsCustomizeOpen(false)}
              className="text-xs h-8"
            >
              Cancel
            </Button>
            <Button
              size="sm"
              onClick={() => {
                setIsCustomizeOpen(false);
                generateScript({
                  physicianName: customPhysicianName || undefined,
                  physicianSpecialty: customPhysicianSpecialty || undefined,
                  medicalDirectorRole: customMedicalDirectorRole || undefined,
                  customStrategyNotes: customStrategyNotes || undefined,
                });
              }}
              className="text-xs h-8 bg-primary text-primary-foreground hover:bg-primary/90"
            >
              Apply & Re-Synthesize
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};
